# Generated by Django 3.1.2 on 2021-07-29 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='my_resume',
            field=models.FileField(blank=True, upload_to='uploads/doc'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to='uploads/images'),
        ),
    ]
