# Generated by Django 3.1 on 2021-09-14 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_auto_20210729_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='my_resume',
            field=models.FileField(upload_to='uploads/doc'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='profile_image',
            field=models.ImageField(upload_to='uploads/images'),
        ),
    ]
